resource "random_id" "random_string_for_web_app_service_plan" { ## This resource generates a random string with
# 8 bytes of length, which will be used later as part of the service plan name.
  byte_length = 8
}

resource "azurerm_service_plan" "faceapp_service_plan" { ## The second resource defined is azurerm_service_plan
#with the name faceapp_service_plan. This resource creates an Azure service plan for the web application.
  name                = "${random_id.random_string_for_web_app_service_plan.dec}-${var.webapp_service_plan_name}" ## The name argument for 
  #the service plan is set to the concatenation of the random string generated by the random_id resource and 
  #the string defined in the webapp_service_plan_name variable.
  resource_group_name = module.container_registry.faceapp_resource_group_name ## The resource_group_name argument
  #is set to the value of the faceapp_resource_group_name output from the container_registry module.
  location            = module.container_registry.faceapp_resource_group_location ## The location argument is 
  #set to the value of the faceapp_resource_group_location output from the container_registry module.
  os_type             = var.webapp_os_type ## The os_type argument is set to the value of the webapp_os_type variable.
  sku_name            = var.webapp_sku_name ## The sku_name argument is set to the value of the webapp_sku_name variable.
}
