## Terraform configuration file that creates an Azure resource group.
# Here's a detailed explanation of each line:

resource "random_id" "random_string_for_rg" { ## This line creates a new Terraform resource of type "random_id"
# with the name "random_string_for_rg". The purpose of this resource is to generate a random string to be used
# in the name of the Azure resource group. The byte_length argument sets the length of the random string in bytes,
# which is 8.
  byte_length = 8
}

resource "azurerm_resource_group" "faceapp_resource_group" { ##  This line creates a new Terraform resource of type "azurerm_resource_group" with the name "faceapp_resource_group". This resource represents an Azure resource group.
  name     = "${random_id.random_string_for_rg.dec}-${var.faceapp_resource_group_name}"  ##  This line sets the name of the Azure resource group to a combination of the random string generated by the random_id resource and the value of the Terraform variable faceapp_resource_group_name. The ${...} syntax is used to reference Terraform resources and variables.
  location = var.faceapp_resource_group_location  ## This line sets the location of the Azure resource group to the value of the Terraform variable faceapp_resource_group_location.
}

output "faceapp_resource_group_name" { ## This line creates an output named "faceapp_resource_group_name". 
#The value of the output is the name of the Azure resource group, which is retrieved using the azurerm_resource_group.faceapp_resource_group.name expression.
 value = azurerm_resource_group.faceapp_resource_group.name
}

output "faceapp_resource_group_location" { ## This line creates an output named "faceapp_resource_group_location". 
  value = azurerm_resource_group.faceapp_resource_group.location ## The value of the output is the location of the Azure resource group, which is retrieved using the azurerm_resource_group.faceapp_resource_group.location expression.
}
